### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by sidyhe** [hprose/hprose-java#19]
首先支持一下Hprose, 使用起来很方便.
我在尝试用Hprose搭建一组服务器, 有一个问题不知如何解决
假设某个请求路径: client->Server B->Server A
若A发生异常, 则最终会反馈给client, 但client不知是A还是B发生了问题
且异常信息没有说明是哪个函数(或调用堆栈)产生了异常
最重要的, Server自己有日志系统, 但Hprose把异常直接反馈给调用方, 导致无法获知并记录日志
希望能有一个统一的异常回调, 能通知发生了异常(方便记录), 然后再反馈给调用方
网上资料太少, 论坛又太冷清, 所以来这里请教, 见谅

**Comment by andot** [comment]
服务器端有个 `HproseServiceEvent`：

```Java
public interface HproseServiceEvent {
    void onBeforeInvoke(String name, Object[] args, boolean byRef, HproseContext context) throws Throwable;
    void onAfterInvoke(String name, Object[] args, boolean byRef, Object result, HproseContext context) throws Throwable;
    Throwable onSendError(Throwable e, HproseContext context) throws Throwable;
    void onServerError(Throwable e, HproseContext context);
}
```

通过实现这个接口，并进行设置，就可以记录异常了。

其中 `onSendError` 是当服务器端异常转发给客户端时触发，`onServerError` 是服务器端无法发送数据给客户端并产生异常时触发。

在 `onSendError` 里面，你还可以抛出一个新的异常或者返回一个新的异常，来替换传入的异常。

**Comment by sidyhe** [comment]
已经解决, 并根据您的指点有所改进, 谢谢.

**Comment by andot** [comment]
不客气
