### ISSUE TITLE
服务器在NAT后，无法使用。

### ISSUE THREAD

**Issue by wxwhaha** [hprose/hprose-java#20]
版本1.5.2 h_for_java8
运行包中带的TCPHello*的例子可以运行。
1. 在本地，如果helloServer和helloClient中的ip任何一个不使用localhost，比如其中一个使用（本机ip）192.168.*.*,另一个使用localhost。连接不成功。 同时使用192.168.*.*是可以的。 server和client中的地址必须写成一模一样才能用吗？
2.server 在远程服务器上，服务器是通过nat分配的公网ip，在服务器本机ping自己的公网ip是ping到的。
所以server使用公网ip会出错。 如果写成它的内网ip，就会重复了第1个问题，客户端写的是公网ip，服务端是自己的内网ip。连接失败。

**Comment by sidyhe** [comment]
这个我觉得是IP的绑定机制有关(系统层面)
如果是0.0.0.0/127.0.0.1/localhost, 则代表监听本地所有网卡
如果是其他某个已分配IP地址, 则仅监听此IP所对应的那个网卡
可能我说的不是太明白, 举个例子
机器上有双网卡, 有两个IP称作A和B
开启一个服务在A上面, 那么B所在网络的机器是无法访问的, 而A所在网络的机器可以访问
若开启一个服务在0.0.0.0上, A和B所在的网络都可以访问的到

**Comment by wxwhaha** [comment]
服务器只用了一个网卡，通过NAT映射的，用公网ip启动的时候就会有问题，并且一个写localhost，一个写ip，在本地测试的时候都会出错。

**Comment by andot** [comment]
监听 0.0.0.0 就可以了。
