### ISSUE TITLE
hprose java

### ISSUE THREAD

**Issue by dqx321** [hprose/hprose-java#22]
android studio 开发的时候。使用hprose2.0里面的推送，jar包在哪里下载。有没有demo.

**Comment by andot** [comment]
https://github.com/hprose/hprose-java/tree/master/dist
java包在这里，主要不要下载 java5 和 java8 的版本，只有 java6 和 java7 的版本支持 android。

例子在这里：https://github.com/hprose/hprose-java/tree/master/example/MyApplication

除了回调时需要注意一下执行线程切换，其它的跟普通 java 程序中使用没有区别。

**Comment by dqx321** [comment]
为什么java8的不支持android，因为我要做的是一个推送的，java7里面还没有这功能，只能使用java8。

**Comment by andot** [comment]
hprose 2.0 for java 都支持推送，跟具体的 JDK 版本没有关系。android 不支持 java8 跟 hprose 也没有关系，是因为 android 本身不支持 java8。
