### ISSUE TITLE
hprose.io.access.PropertyAccessor在序列化和反序列化过程中如果出现异常，堆栈信息不完整

### ISSUE THREAD

**Issue by wtslh** [hprose/hprose-java#27]
v2.0.33，对实体的序列化和反序列化过程中如果出现异常。以getter为例，调用getter并在getter内部出现异常后，现在的catch会捕获异常，然后throw new HproseException(e.getMessage());
这种情况下，异常堆栈丢失，导致序列化过程出现异常后很难排查错误原因。
![image](https://user-images.githubusercontent.com/2245560/31430217-cce31410-aea2-11e7-9375-9cf869000cda.png)

**Comment by andot** [comment]
那有什么好的解决方案吗？

**Comment by wtslh** [comment]
本来是想换成HproseException的另外两个构造器将异常传递下去，然后在事件处理器的onSendError中捕获和打印，但发现无效。
因为项目紧张，所以我暂时就在PropertyAccessor的序列化和反序列化方法中直接添加了日志和打印。
但这样肯定不是最好的方案了，因为依赖了日志组件并且没有将异常传递出去。

**Comment by andot** [comment]
要改善这个问题，恐怕需要抛弃掉对Java 1.5的支持，只支持1.6以上的Java版本才行。1.6以上的IOException构造函数支持传入一个异常对象参数，而不仅仅是一个Message。这样就可以保留堆栈信息了。
