### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by danielsawan** [hprose/hprose-java#29]
Hi !

I was wondering if there is a built in security while calling a method in hprose. I mean actually i guess the server just bind a port and accept every incoming communication including illegit ones.

**Comment by andot** [comment]
You can define an `InvokeHandler` to prevent illegal clients.

```java
public interface InvokeHandler {
    Promise<Object> handle(String name, Object[] args, HproseContext context, NextInvokeHandler next);
}
```

You can cast `context` to `HttpContext` on servlet server or `TcpContext` on TCP server. And then, you can get the client IP or something you need.

**Comment by danielsawan** [comment]
Thanks, I manage to get the request IP from TcpContext 👍
