### ISSUE TITLE
我做了一个RPC的性能测试，hprose表现不是非常好

### ISSUE THREAD

**Issue by hank-whu** [hprose/hprose-java#35]
我做了一个rpc benchmark：https://github.com/hank-whu/rpc-benchmark
会长期维护不定期发布结果的，欢迎指出代码或者配置错误，我会及时跟进并重新进行benchmark

本次测试结果：https://www.jianshu.com/p/18c95649b1a4

**Comment by andot** [comment]
我提交了一个修改，hprose 客户端是线程安全的，内置连接池，在并发时只需要1个客户端，如果测试时，每个线程都新开一个客户端，连接池就毫无用处了。另外，默认是半双工模式，一个连接同时只能跑一个请求，而且连接池有个最大连接数限制，因此，在这个模式下效率也不高，改为全双工模式的话，一个连接可以同时跑多个请求，这样速度会增加很多。

**Comment by hank-whu** [comment]
已经合并，多谢支持
