### ISSUE TITLE
查询单个对象的时候 可以  但是 查询 对象集合的时候 就不行了 List<A>

### ISSUE THREAD

**Issue by allenwtl** [hprose/hprose-java#46]
_Originally posted by @andot in https://github.com/hprose/hprose-java/issues/43#issuecomment-389490414_

**Comment by andot** [comment]
如果你不是直接使用unserialize方法，那你应该是在反序列化的一段没有注册该类型。请参见：https://github.com/hprose/hprose-java/wiki/Hprose-%E5%BA%8F%E5%88%97%E5%8C%96#register-%E6%96%B9%E6%B3%95

**Comment by allenwtl** [comment]
我是使用 motan 框架 他们框架中使用 hprose 进行序列化 List<A>  难道不是自动进行 注册和检测 吗

**Comment by allenwtl** [comment]
是返回的结果 是单个对象的时候  就可以  但是返回的结果是List 集合的时候 就不行了

**Comment by allenwtl** [comment]
明白了
