### ISSUE TITLE
JSON format support?

### ISSUE THREAD

**Issue by xzzh999** [hprose/hprose-java#51]
Hi~
Great work!

When hprose-java's  filter can add support for JSON convert? any plans?

**Comment by andot** [comment]
Hprose for Java 现在仅使用 JDK 来实现，但是 JDK 并没有提供 JSON 支持，所以这个 hprose 2.0 版本不会增加对 JSON 的支持了。Hprose 3.0 会增加一个单独的 JSONRPC 的编码器。

**Comment by xzzh999** [comment]
@andot 
Thanks.
